# Vault Path: app-configuration/ferma-congress/prod/entity-extraction-agent-drug-worker/values.yaml
# Key: values

chart_version: 3.1.0
kind: keda
product: ferma-congress

application_config:
  name: entity-extraction-agent-drug-worker
  type: backend

  image:
    name: entity-extraction-agent

  resource:
    preset: micro  # 250m CPU / 512Mi

  entrypoint:
    enabled: true
    command: "python -m src.temporal.workers.drug_worker"

  filebeat:
    enabled: false

  volume_mount: "/app/entity-extraction-agent"
  nodepool: autopilot

keda_config:
  type: temporal
  max_replicas: 5
  pollingInterval: 15

  temporal:
    namespace: entity-extraction-agent
    taskqueue: drug-activities
    endpoint: prod-temporal-server-service.prod-temporal-app.svc.cluster.local:7233
    queuesize: "15"
